#! /usr/bin/env python3

import sys
import RPi.GPIO as GPIO
from time import sleep
sys.path.append(r'/opt/quick2wire-python-api')
from quick2wire.parts.pcf8591 import *
from quick2wire.i2c import I2CMaster

### l298n controller
### en[a|b][0|1] pins enable the motor
enb0 = int(20)
enb1 = int(21)

GPIO.setmode(GPIO.BCM)
GPIO.setup(enb0, GPIO.OUT)
GPIO.setup(enb1, GPIO.OUT)

### BASE_ADDRESS is 0x48 default
address = int(sys.argv[1]) if len(sys.argv) > 1 else BASE_ADDRESS
pin_index = int(sys.argv[2]) if len(sys.argv) > 2 else 0


with I2CMaster() as i2c:
  adc = PCF8591(i2c, FOUR_SINGLE_ENDED)
  sei = adc.single_ended_input_count()
  print('single ended input count: %s' % sei)
  aout = adc.output()
  print('AOUT: %s' % aout)
  ### assuming 'pin' is AIN0?
  pin = adc.single_ended_input(pin_index)
    
  while True:
    pinval = int(pin.value * 100)
    pinval = int(1) if pinval < int(1) else pinval
    print(pinval)
    pwma0 = GPIO.PWM(enb0, pinval)
    pwma1 = GPIO.PWM(enb1, pinval)
    pwma0.start(15)
    pwma1.start(15) 
    #print("read: {} : {}".format(count, pin.value))
    sleep(0.5)

